scale = tas_random_range(0.2, 1)
image_xscale = scale
image_yscale = scale
image_alpha = 0
max_alpha = 0.5 + tas_random(0.5)
fadeout = 0
alarm[0] = 10 + tas_random(300)
direction = tas_random(360)
speed = tas_random(0.5)
