spark = instance_create(x, (y + 4 + tas_random(24)), oFXAnimSpark)
spark.sprite_index = sBatterySpark
spark.image_speed = 0.5
spark.additive = 1
spark.image_xscale = tas_choose(1, -1)
spark.image_yscale = tas_choose(1, -1)
spark.image_angle = tas_random(360)
spark.depth = -1
alarm[1] = 10 + tas_random(30)
